name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  MACRO: "@openhands-agent"
  MAX_ITERATIONS: 50

jobs:
  get-env:
    name: Get Environment vars
    runs-on: ubuntu-latest
    if: |
      ${{
        github.event.label.name == 'fix-me' ||
        (github.event_name == 'issue_comment' && 
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER'))
      }}
    outputs:
      MACRO: ${{ env.MACRO }}
      MAX_ITERATIONS: ${{ env.MAX_ITERATIONS }}
    steps:
      - run: echo "null"

  call-openhands-resolver:
    needs: [get-env]
    if: ${{ startsWith(github.event.comment.body, needs.get-env.outputs.MACRO) || github.event.label.name == 'fix-me' }}
    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@bug/comment-invocation
    with:
      macro: ${{ needs.get-env.outputs.MACRO }}
      max_iterations: ${{ fromJSON(needs.get-env.outputs.MAX_ITERATIONS) }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
